---
- name: "TERM_RUST_INSTALL - Install clang"
  ansible.builtin.package:
    name: clang
    state: present

- name: "TERM_RUST_INSTALL - Create tools directory"
  ansible.builtin.file:
    path: /usr/share/mps/tools/rustup
    state: directory
    mode: "0755"

- name: "TERM_RUST_INSTALL - Download rustup.sh"
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /usr/share/mps/tools/rustup/rustup.sh
    mode: "0755"
