---
- name: Install clang for cargo
  ansible.builtin.package:
    name: clang
    state: present

- name: Ensure rustup tools directory exists
  ansible.builtin.file:
    path: /usr/share/mps/tools/rustup
    state: directory
    mode: "0755"

- name: Download rustup installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /usr/share/mps/tools/rustup/rustup.sh
    mode: "0755"
