---
- name: "TERM_BASH_INSTALL - Install bash-completion"
  ansible.builtin.package:
    name: bash-completion
    state: present
  when: bash_install_bash_completion | bool

- name: "TERM_BASH_INSTALL - Install fun packages"
  ansible.builtin.package:
    name: "{{ bash_fun_packages }}"
    state: present
  when: bash_fun_packages | length > 0

- name: "TERM_BASH_INSTALL - Create system aliases directory"
  ansible.builtin.file:
    path: /etc/bash_aliases.d
    state: directory
    mode: "0755"
  when: bash_install_aliases | bool

- name: "TERM_BASH_INSTALL - Deploy system alias files"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/etc/bash_aliases.d/"
    dest: /etc/bash_aliases.d/
    mode: "0644"
    directory_mode: true
  when: bash_install_aliases | bool
