---
namespace: odem
name: terminal
version: 0.3.2
readme: README.md
authors:
  - foo <bar@baz.com>
description: Terminal environment and developer tools
license:
  - GPL-3.0-or-later
tags:
  - linux
  - terminal
  - shell
  - fonts
  - python
  - rust
  - odem
repository: https://github.com/my-perfect-system/odem-terminal
documentation: https://github.com/my-perfect-system/odem-terminal
homepage: https://github.com/my-perfect-system/odem-terminal
issues: https://github.com/my-perfect-system/odem-terminal/issues
build_ignore:
  .ansible-lint
  .yamllint
  - .git
  - .github
  - .gitignore
  - "*.tar.gz"
  - .ansible
dependencies:
  odem.base: ">=0.1.0"
  ansible.posix: ">=1.0.0"
