argument_specs:
  main:
    short_description: Configure vim dotfiles per user
    options:
      vim_enable_vim_nox:
        type: bool
        required: false
        default: true
        description: Install vim-nox and vim plugin packages
      vim_enable_lua:
        type: bool
        required: false
        default: true
        description: Install lua development packages
      vim_enable_xclip:
        type: bool
        required: false
        default: true
        description: Install xclip package
