---

# Feature toggles — naming pattern: <rolename>_enable_<feature>

vim_enable_vim_nox: true
vim_enable_lua: true
vim_enable_xclip: true

# Regular config
vim_repo: "https://github.com/my-perfect-system/mps-vim.git"
vim_repos_dir: "{{ common_default_repo_dir_mps }}"
vim_version: "main"

