return {
  require("appearance.bufferline"),
  require("appearance.alpha"),
  require("appearance.barbecue"),
  require("appearance.scrollbar"),
  require("appearance.indent-blankline"),
  require("appearance.colorful-winsep"),
  require("appearance.symbols-outline"),
  require("appearance.gitsigns"),
  require("appearance.colorizer"),
  require("appearance.windows"),
  require("appearance.tokyonight"),
  require("appearance.gruvbox"),
  require("appearance.dressing"),
  require("appearance.noice"),
  require("appearance.lualine"),
  require("appearance.yank-highlight"),
}
