---
galaxy_info:
  author: foo <bar@baz.com>
  description: "Deploy per-user utility scripts"
  min_ansible_version: "2.20.0"
  license: GPL-3.0-or-later
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - debian
    - debian13
    - trixie
    - terminal
    - scripts
    - mps-terminal
dependencies: []
