---
- name: Install kitty package
  ansible.builtin.package:
    name: kitty
    state: present

- name: Set kitty as x-terminal-emulator alternative
  ansible.builtin.command:
    cmd: update-alternatives --set x-terminal-emulator /usr/bin/kitty
  changed_when: false
  failed_when: false
  when: kitty_enable_alternatives | bool
