---
- name: "TERM_KITTY_MAIN - Install system packages"
  ansible.builtin.include_tasks: install.yml

- name: "TERM_KITTY_MAIN - Configure per-user kitty"
  ansible.builtin.include_tasks: configure.yml
