argument_specs:
  main:
    short_description: Configure kitty terminal emulator per user
    options:
      kitty_enable_alternatives:
        type: bool
        required: false
        default: true
        description: Set kitty as default x-terminal-emulator via update-alternatives
