---
galaxy_info:
  author: foo <bar@baz.com>
  description: "Configure bash shell"
  min_ansible_version: "2.16.0"
  license: GPL-3.0-or-later
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - debian
    - debian13
    - trixie
    - terminal
    - bash
    - odem-terminal
dependencies:
  - role: odem.base.identity
