---
- name: Terminal full install
  hosts: all
  become: true
  roles:
    - role: mps.terminal.bash
    - role: mps.terminal.fonts
    - role: mps.terminal.vim
    - role: mps.terminal.tmux
    - role: mps.terminal.kitty
    - role: mps.terminal.rust
    - role: mps.terminal.python
    - role: mps.terminal.nvim
    - role: mps.terminal.scripts
    - role: mps.terminal.skeletons
