# /home/jb/.config/tmuxinator/vibe.yml

name: work
root: ~/repo/github/odem/unattend-my-iso/
windows:
  - editor:
      layout: "b7f5,191x44,0,0[191x32,0,0{122x32,0,0,257,68x32,123,0,258},191x11,0,33{95x11,0,33,259,95x11,96,33,260}]"
      panes:
        - "cd $HOME/repo/gitlab/idris/idris-iso-config ; n"
        - "cd $HOME/repo/gitlab/idris/idris-iso-config"
        - bash
        - "cd $HOME/repo/gitlab/idris/idris-iso-config"
