---
- name: "TERM_NVIM_INSTALL - Install apt dependencies"
  ansible.builtin.package:
    name:
      - lazygit
      - make
      - gcc
      - gdb
      - wget
      - bzip2
      - curl
      - build-essential
      - lldb
      - libncurses-dev
      - ruby
      - npm
      - fzf
      - fd-find
      - rr
      - ripgrep
      - shellcheck
      - xclip
      - xsel
      - luarocks
      - chktex
      - ansible-lint
      - python3
      - python3-venv
      - python3-pip
      - black
      - flake8
      - pylint
      - mypy
      - pandoc
      - python3-neovim
      - python3-pynvim
    state: present
  when: nvim_install_apt_deps | bool

- name: "TERM_NVIM_INSTALL - Install npm tools"
  ansible.builtin.command:
    cmd: npm install -g neovim vint luacheck
    creates: /usr/lib/node_modules/neovim
  when: nvim_install_npm_tools | bool

- name: "TERM_NVIM_INSTALL - Create nvim tools directory"
  ansible.builtin.file:
    path: /usr/share/mps/tools/nvim/
    state: directory
    mode: "0755"
  when: nvim_install_tarball | bool

- name: "TERM_NVIM_INSTALL - Download Neovim tarball"
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.12.1/nvim-linux-x86_64.tar.gz
    dest: /usr/share/mps/tools/nvim/
    mode: "0644"
  when: nvim_install_tarball | bool

- name: "TERM_NVIM_INSTALL - Extract Neovim tarball"
  ansible.builtin.unarchive:
    src: /usr/share/mps/tools/nvim/nvim-linux-x86_64.tar.gz
    dest: /usr/share/mps/tools/nvim/
    remote_src: true
  when: nvim_install_tarball | bool

- name: "TERM_NVIM_INSTALL - Remove /usr/bin/nvim if present"
  ansible.builtin.file:
    path: /usr/bin/nvim
    state: absent
  failed_when: false
  when: nvim_install_tarball | bool

- name: "TERM_NVIM_INSTALL - Create nvim symlink"
  ansible.builtin.file:
    src: /usr/share/mps/tools/nvim/nvim-linux-x86_64/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
  when: nvim_install_tarball | bool
