---
- name: "TERM_NVIM_MAIN - Resolve users"
  ansible.builtin.include_tasks: resolve.yml

- name: "TERM_NVIM_MAIN - Install system packages"
  ansible.builtin.include_tasks: install.yml

- name: "TERM_NVIM_MAIN - Configure per-user nvim"
  ansible.builtin.include_tasks: configure.yml

- name: "TERM_NVIM_MAIN - Install nvim tools"
  ansible.builtin.include_tasks: tools.yml
