---
- name: Install nvim packages and binary
  ansible.builtin.include_tasks: install.yml

- name: Configure per-user nvim dotfiles
  ansible.builtin.include_tasks: configure.yml

- name: Install nvim companion tools
  ansible.builtin.include_tasks: tools.yml
